export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORY_START: 'category/FETCH_CATEGORY_START',
    FETCH_CATEGORY_SUCCES: 'category/FETCH_CATEGORY_SUCCES',
    FETCH_CATEGORY_FAILED: 'category/FETCH_CATEGORY_FAILED',
}